name = "dashboard"
compatibility_date = "2026-07-03"
pages_build_output_dir = "dist"

[vars]
ENVIRONMENT = "production"
ACCESS_TEAM_DOMAIN = "https://sinopharm-dashboard.cloudflareaccess.com"
ACCESS_AUD = "0d712017c84a1777f9cdfcb8b852daff05d5cd38de610a0c435bb4f33b45d189"
MAX_UPLOAD_BYTES = "20971520"
DEEPSEEK_MODEL = "deepseek-v4-flash"
DEEPSEEK_BASE_URL = "https://api.deepseek.com"

# Production D1
[[d1_databases]]
binding = "DB"
database_name = "report-storage-production"
database_id = "d0d344e9-70dd-4924-954a-f6f7a8d384c2"

# Production R2
[[r2_buckets]]
binding = "FILES_BUCKET"
bucket_name = "report-files-production"

[env.preview.vars]
ENVIRONMENT = "preview"
ACCESS_TEAM_DOMAIN = "https://sinopharm-dashboard.cloudflareaccess.com"
ACCESS_AUD = "b9097eabea6a1f521cb506952f82dafd4b8174a9ea3914280d83d5b8a21b7c65"
MAX_UPLOAD_BYTES = "20971520"
DEEPSEEK_MODEL = "deepseek-v4-flash"
DEEPSEEK_BASE_URL = "https://api.deepseek.com"

# Preview D1
[[env.preview.d1_databases]]
binding = "DB"
database_name = "report-storage-preview"
database_id = "ec2be275-f027-4281-bcd8-f02c93c82867"

# Preview R2
[[env.preview.r2_buckets]]
binding = "FILES_BUCKET"
bucket_name = "report-files-preview"
